services:
  nginx:
    image: tiangolo/nginx-rtmp:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - streams-volumes:/hls/live
    ports:
      - "1935:1935"
    depends_on:
      - auth_server
    
  playback_server:
    build: 
      dockerfile: ./Dockerfile.playback
      context: .
    ports:
      - "8001:8001"
    depends_on:
      - auth_server
      - nginx
  
  auth_server:
    build: 
      dockerfile: ./Dockerfile.auth
      context: .
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
  
  postgres:
    image: postgres
    restart: always
    hostname: postgres
    volumes:
      - ./scripts/1_init.sql:/docker-entrypoint-initdb.d/1_init.sql
      - ./scripts/2_stream_keys_populate.sql:/docker-entrypoint-initdb.d/2_stream_keys_populate.sql
    environment:
      POSTGRES_PASSWORD: password!
      POSTGRES_DB: streamkeys
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 2s
      retries: 30

volumes:
  streams-volumes:

