FROM golang:1.22
WORKDIR /app

COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o server ./cmd/server/main.go

FROM scratch
COPY --from=builder /app/server /server

ENTRYPOINT [ "/server" ]

EXPOSE 8000